typography_spectrum: 0.4267083019949496
color:
  brandColors:
    - '#747474'
    - '#4E4E4E'
    - '#8F8F8F'
    - '#1F1F1F'
    - '#D8D8D8'
  brandStrength: 0.446242593228817
  lightness: 0.6087289119604975
  saturation: 0.32402325863949955
  rhythmicContrast: 0.2550327740609646
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.37561103445477784
analytics:
  google: null
  facebook: null
  twitter: null
name: Publications & images from Julius Barsi
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Barsi et al 2005
    url: 'https://drive.google.com/open?id=0B5GkdNXImP2uUEgxdkdJRUl6czg'
    type: external
favicon: null
title: ' Biological research'
description: systems developmental biology
purpose: []
