typography_spectrum: 0.7680281072389334
color:
  brandColors:
    - '#757575'
    - '#2c2c2c'
    - '#060606'
    - '#ababab'
    - '#e0e0e0'
  brandStrength: 0.0625
  lightness: 0.4375
  saturation: 0.9375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.82539
analytics:
  google: null
  facebook: null
  twitter: null
name: Publications and research related images from Julius Barsi
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ' research related images from Julius Barsi'
description: systems developmental biology
purpose: []
