name: systems developmental biology & research related images from Julius Barsi
favicon: null
layout_spectrum: 0.82539
typography_spectrum: 0.7680281072389334
title: systems developmental biology & research related images from Julius Barsi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#757575'
    - '#2c2c2c'
    - '#060606'
    - '#ababab'
    - '#e0e0e0'
  brandStrength: 0.0625
  lightness: 0.4375
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
